create table  IF NOT EXISTS contact
(
    id bigint generated by default as identity (start with 1) primary key,
    first_name varchar(200) not null,
    second_name varchar(200) not null,
    email varchar(200) not null,
    phoneNumber varchar(200) not null,
    company_id bigint,
    comment varchar(400) not null,
    stat varchar(400),
    created_date date,
    last_modified_date date
);
create table IF NOT EXISTS company
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_company primary key (id)
);


